"""add_image_url_to_categories

Revision ID: da887d7219c5
Revises: 86867ea0ecef
Create Date: 2025-11-28 17:09:11.351697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da887d7219c5'
down_revision = '86867ea0ecef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_payment_reference'), 'webhook_events', ['payment_reference'], unique=False)
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pending_checkouts', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key, auto-incrementing',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pending_checkouts', 'idempotency_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Unique key to prevent duplicate checkout submissions',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Paystack payment reference for tracking',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'checkout_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON string containing cart items, customer details, and payment info',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Status: pending, completed, expired, or failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('pending_checkouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when checkout was initiated',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pending_checkouts', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this pending checkout expires (typically 1 hour after creation)',
               existing_nullable=False)
    op.drop_index('ix_pending_checkouts_expires_at', table_name='pending_checkouts')
    op.drop_index('ix_pending_checkouts_status', table_name='pending_checkouts')
    op.drop_constraint('pending_checkouts_idempotency_key_key', 'pending_checkouts', type_='unique')
    op.drop_constraint('pending_checkouts_payment_reference_key', 'pending_checkouts', type_='unique')
    op.drop_table_comment(
        'pending_checkouts',
        existing_comment='Stores pending checkout data before payment confirmation via Paystack webhook',
        schema=None
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_table_comment(
        'pending_checkouts',
        'Stores pending checkout data before payment confirmation via Paystack webhook',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('pending_checkouts_payment_reference_key', 'pending_checkouts', ['payment_reference'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('pending_checkouts_idempotency_key_key', 'pending_checkouts', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_pending_checkouts_status', 'pending_checkouts', ['status'], unique=False)
    op.create_index('ix_pending_checkouts_expires_at', 'pending_checkouts', ['expires_at'], unique=False)
    op.alter_column('pending_checkouts', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this pending checkout expires (typically 1 hour after creation)',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when checkout was initiated',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pending_checkouts', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: pending, completed, expired, or failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('pending_checkouts', 'checkout_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON string containing cart items, customer details, and payment info',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               comment='Paystack payment reference for tracking',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               comment='Unique key to prevent duplicate checkout submissions',
               existing_nullable=False)
    op.alter_column('pending_checkouts', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key, auto-incrementing',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'image_url')
    op.alter_column('admin_users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_webhook_events_payment_reference'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
