# Database
DB_POOL_SIZE = 10
DB_MAX_OVERFLOW = 20
DB_POOL_TIMEOUT = 30

# Cache
CACHE_DEFAULT_TTL = 3600  # 1 hour
CACHE_PRODUCT_TTL = 1800  # 30 minutes
CACHE_ORDER_TTL = 300     # 5 minutes

# Payment
PAYSTACK_KOBO_MULTIPLIER = 100
PAYSTACK_MIN_AMOUNT = 100  # ₦1.00 in kobo
PAYSTACK_MAX_AMOUNT = 10000000  # ₦100,000 in kobo

# Rate Limiting
RATE_LIMIT_AUTH = "5/minute"
RATE_LIMIT_CHECKOUT = "3/minute"
RATE_LIMIT_API = "100/minute"

# User Roles
ADMIN_ROLE = "admin"
CUSTOMER_ROLE = "customer"

# Order Status
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_CONFIRMED = "confirmed"
ORDER_STATUS_CANCELLED = "cancelled"
ORDER_STATUS_COMPLETED = "completed"

# Payment Status
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_REFUNDED = "refunded"

# String Lengths
NAME_MIN_LENGTH = 1
NAME_MAX_LENGTH = 255
PHONE_MIN_LENGTH = 7
PHONE_MAX_LENGTH = 20
ADDRESS_MIN_LENGTH = 10
ADDRESS_MAX_LENGTH = 1000
NOTES_MIN_LENGTH = 1
NOTES_MAX_LENGTH = 1000
IDEMPOTENCY_KEY_MIN_LENGTH = 1
IDEMPOTENCY_KEY_MAX_LENGTH = 255
PAYMENT_METHOD_MAX_LENGTH = 50

PRODUCT_NAME_MAX_LENGTH = 255
CATEGORY_NAME_MAX_LENGTH = 100
VARIANT_SIZE_MAX_LENGTH = 50
VARIANT_COLOR_MAX_LENGTH = 50
VARIANT_SKU_MAX_LENGTH = 100
IMAGE_URL_MAX_LENGTH = 500
IMAGE_ALT_TEXT_MAX_LENGTH = 255
ORDER_NUMBER_MAX_LENGTH = 50
ORDER_STATUS_MAX_LENGTH = 50
PAYMENT_STATUS_MAX_LENGTH = 50
PAYMENT_REFERENCE_MAX_LENGTH = 100
CUSTOMER_EMAIL_MAX_LENGTH = 255
CUSTOMER_PHONE_MAX_LENGTH = 50
USERNAME_MAX_LENGTH = 50
PASSWORD_HASH_MAX_LENGTH = 255
ROLE_MAX_LENGTH = 50